### PR TITLE
Allow make_declarative_base to take a custom metaclass as input. 

### PR DESCRIPTION
**Pull request by elidchan**
Any custom metaclass should extend ModelMeta, of course.

### CODE REVIEW

**Comment by dgilland** [comment]
Groovy! Thanks @elidchan!

Want to add yourself to `AUTHORS.rst`? Can include that with this PR.

BTW, the build failure looks to be related to some change in SQLAlchemy thats unrelated to this PR. If you're feeling ambitious, feel free to tackle that; otherwise, I'll look into as soon as I can.

**Comment by elidchan** [comment]
@dgilland: Happy to help where I can!

I've added myself to AUTHORS.rst at the bottom (based on chronological
order).

I also just fixed a typo in the quickstart guide
<https://github.com/dgilland/alchy/commit/1f3e82076ff63bde02e361d38ec3d1dc76f4ac75>
.

I started looking at the build failure, but I think it's a bit over my head
right now.

On a separate note, would you be able to point me to an example of how you
recommend using alchy in conjunction with flask (even better with flask
blueprints)? I'm trying to determine where I should be using alchy Manager
vs. flask SQLAlchemy.

Thanks!
Eli

On Fri, Mar 11, 2016 at 9:08 AM, Derrick Gilland <notifications@github.com>
wrote:

> Groovy! Thanks @elidchan <https://github.com/elidchan>!
>
> Want to add yourself to AUTHORS.rst? Can include that with this PR.
>
> BTW, the build failure looks to be related to some change in SQLAlchemy
> thats unrelated to this PR. If you're feeling ambitious, feel free to
> tackle that; otherwise, I'll look into as soon as I can.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dgilland/alchy/pull/27#issuecomment-195405545>.
>



-- 
Eli Chan
Founder & CEO  |  Intertwine.io
512.586.8068  |  eli.chan@intertwine.io
www.linkedin.com/in/elidchan

**Comment by dgilland** [comment]
There's [Flask-Alchy](https://github.com/dgilland/flask-alchy) which I'm the author of. It's basically a drop-in replacement for `Flask-SQLAlchemy` with some minor changes to the base `SQLAlchemy` class. You would use `Flask-Alchy` just like you use `Flask-SQLAlchemy`. However, I have not tested it with the latest version of `Flask-SQLAlchemy` so there may be some compatibility issues now (or not).

No worries about the build failure issue. I'll address it when I can.

**Comment by dgilland** [comment]
FYI, this change has been released as [v2.1.0](https://pypi.python.org/pypi/alchy/2.1.0).

Thanks again for the contribution! :+1:

**Comment by elidchan** [comment]
Cool, thanks for the update!

**Pull request merged**
