### PR TITLE
Add support for callable __table_args__ and __local_table_args__.

### PR DESCRIPTION
**Pull request by seth-p**

### CODE REVIEW

**Comment by seth-p** [comment]
Afraid I can't figure out why the 2.6 test failed: https://travis-ci.org/dgilland/alchy/jobs/47381387.
The 2.7, 3.3, and 3.4 tests passed: https://travis-ci.org/dgilland/alchy/builds/47381386.

**Comment by dgilland** [comment]
Looks like a Python 2.6 regression in `astroid` which is required by `pylint`: https://travis-ci.org/dgilland/alchy/jobs/47381387#L500 (line 500)

Seems astroid was updated on 1/16/15: https://pypi.python.org/pypi/astroid/1.3.4

The issue is this line in astroid.modutils: https://bitbucket.org/logilab/astroid/src/bbeb96a16e25b2ac106f38eb830026de9a1be8b0/astroid/modutils.py?at=default#cl-69

The syntax used is not compatible with Python 2.6. It's also the same kind of syntax that caused alchy to fail on Travis with Python 2.6 due to the version of pylint being used at the time.

The easiest fix for this would be to pin astroid to a previous version. Version 1.3.2 may work. It was released 11/22/2014 and it's version of modutils doesn't contain the Python 2.6 syntax issue.

**Comment by seth-p** [comment]
Added "astroid<=1.3.2" to requirements.txt, which fixed the Python 2.6 problem.

**Comment by dgilland** [comment]
Thanks!

**Pull request merged**
